import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID ?? null,
    NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL ?? null,
    NEXT_PUBLIC_RPC_FALLBACK_URL: process.env.NEXT_PUBLIC_RPC_FALLBACK_URL ?? null,

    NEXT_PUBLIC_PRESALE_ADDRESS: process.env.NEXT_PUBLIC_PRESALE_ADDRESS ?? null,
    NEXT_PUBLIC_USDT_ADDRESS: process.env.NEXT_PUBLIC_USDT_ADDRESS ?? null,
    NEXT_PUBLIC_DDC_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_DDC_TOKEN_ADDRESS ?? null,

    NEXT_PUBLIC_RECORDER_ADDRESS: process.env.NEXT_PUBLIC_RECORDER_ADDRESS ?? null,
    NEXT_PUBLIC_REWARD_POOL_ADDRESS: process.env.NEXT_PUBLIC_REWARD_POOL_ADDRESS ?? null,

    NEXT_PUBLIC_TREASURY_ADDRESS: process.env.NEXT_PUBLIC_TREASURY_ADDRESS ?? null,
    NEXT_PUBLIC_TREASURY_VAULT_ADDRESS: process.env.NEXT_PUBLIC_TREASURY_VAULT_ADDRESS ?? null,

    NEXT_PUBLIC_TEAM_VAULT_ADDRESS: process.env.NEXT_PUBLIC_TEAM_VAULT_ADDRESS ?? null,
    NEXT_PUBLIC_ADVISORS_VAULT_ADDRESS: process.env.NEXT_PUBLIC_ADVISORS_VAULT_ADDRESS ?? null,

    NEXT_PUBLIC_MONTHLY_OPS_VAULT_ADDRESS:
      process.env.NEXT_PUBLIC_MONTHLY_OPS_VAULT_ADDRESS ?? null,

    NEXT_PUBLIC_ADAMAS_GRANT_VAULT_ADDRESS:
      process.env.NEXT_PUBLIC_ADAMAS_GRANT_VAULT_ADDRESS ?? null,

    NEXT_PUBLIC_WC_PROJECT_ID:
      process.env.NEXT_PUBLIC_WC_PROJECT_ID ? "set" : null,
  });
}
